### ISSUE TITLE
MSBuild.exe doesn't exit

### ISSUE THREAD

**Issue by jboelter** [MarcStan/Resource.Embedder#1]
The package works great, however it appears to keep MSBuild.exe running.  The handles to the files prevent the build server from cleaning up the checkout directory.

![image](https://cloud.githubusercontent.com/assets/3619564/7480085/da6e22f0-f31a-11e4-8cd4-14527c127b94.png)

**Comment by MarcStan** [comment]
Can you try what was suggested in [this thread](https://github.com/Fody/Fody/issues/48) ("Turning of node reuse with /nr:false seems to fix the problem")?

I don't do anything specifically that would keep MS build around and just tested it locally: once I kill MSBuild manually I can delete the director (MSBuild.exe will also be terminated when VS closes or on the Build server after the 15min timeout).

**Comment by jboelter** [comment]
I ended up finding the same solution.  Confirmed that it works.
