### ISSUE TITLE
It doesnt embed dll

### ISSUE THREAD

**Issue by Azim-D3Tm** [MarcStan/Resource.Embedder#10]
Ok, so i have a dll dependency i want to embed, and readme here clearly stays that it works 'out of the box', when actually it doesnt.
When doing "build" or "rebuild", it says "Nothing to embed! Skipping (filename.exe)", completely ignoring the dll i want to embed.
What properties should dll have to be embeded?

**Comment by MarcStan** [comment]
My tool only embeds **localization** assemblies that are auto generated for each .resx translation file (also known as satellite assemblies).

If you want to embed reference dlls then [Fody.Costura](https://github.com/Fody/Costura) is the tool you need to use.

**Comment by Azim-D3Tm** [comment]
Ah, i see. Visual Studio was giving out that package instead of Fody.Costura for whatever reason ._.
