### ISSUE TITLE
.NET Core / standard unsupported?

### ISSUE THREAD

**Issue by radevop** [MarcStan/Resource.Embedder#11]
Hello,

I am trying to use your tool with TargetFrameworks **netstandard2.0**, **netcoreapp2.1**, **net471**. Everything is fine with **net471**. But with **netcoreapp2.1**, **net471** I am getting following errors on the build:

`MSBUILD : error : Failed injecting code. Sequence contains no matching element`
`MSBUILD : error : Failed to inject required code into assembly: ...path\xResources.dll`

How I understand its failed somewhere inside CecilBasedCodeInjector class in Inject method.

**Comment by MarcStan** [comment]
Yes it's not supported yet.
I'm still using version 0.9.4 of Cecil and .Net Standard support only exists starting with 0.10.

Unfortunately there are a lot of breaking changes between the two Cecil versions and I haven't gotten around to updating yet.

**Comment by MarcStan** [comment]
I just published version 2.0 which now supports .Net Standard 2+ and .Net Core 2+
