### ISSUE TITLE
WEB problems

### ISSUE THREAD

**Issue by tdsrhh** [MarcStan/Resource.Embedder#12]
When using the resource embedder in a asp.net project it works during Build. 

BUT when we run a Publish we get the following errors.

Copying all files to temporary location below for package/publish:
4>obj\Release\AspnetCompileMerge\Source.
4>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\VisualStudio\v15.0\Web\Transform\Microsoft.Web.Publishing.AspNetCompileMerge.targets(615,5): Error : Copying file bin\en-US\TDS.WebService.Mobile.NMA.Client.resources.dll to obj\Release\AspnetCompileMerge\Source\bin\en-US\TDS.WebService.Mobile.NMA.Client.resources.dll failed. Could not find file 'bin\en-US\TDS.WebService.Mobile.NMA.Client.resources.dll'.
4>
========== Build: 3 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 1 failed, 0 skipped ==========

Any ideas how to solve this ?

**Comment by MarcStan** [comment]
This is a bug on my end. I haven't actually used the combination of resource embedder and publishing web apps.

I am able to reproduce and I found a workaround until I can fix it.

Add this to your publish profile:

``` xml
  <ItemGroup>
    <ExcludeFromPackageFiles Include="bin\<langIsoCode>\<projectName>.resources.dll">
      <FromTarget>CollectFilesFromIntermediateSatelliteAssembliesWithTargetPath</FromTarget>
    </ExcludeFromPackageFiles>
  </ItemGroup>
```

For some reason wildcards aren't working for me, even though apparently they [should be possible](https://stackoverflow.com/a/25629030). So you'll have to add each resource file path manually (e.g. "bin\de\MyApp.resources.dll").

**Comment by MarcStan** [comment]
Future pointers for myself:

New target that modifies package files before packaging via:

``` xml
<Target Name="ExcludeMergedResources" AfterTargets="CollectFilesFromIntermediateSatelliteAssembliesWithTargetPath">
  <Message Text="TODO Filter this list and exclude all injected translations: %(FilesForPackagingFromProject.Identity)" Importance="High" />
</Target>
```

https://blog.samstephens.co.nz/2010/10/18/msbuild-including-extra-files-multiple-builds/

**Comment by MarcStan** [comment]
Publish should work as of version 2.0.
