### ISSUE TITLE
System.BadImageFormatException

### ISSUE THREAD

**Issue by RayCarrot** [MarcStan/Resource.Embedder#13]
Since today I can't seem to consistently run my application while using this package. Most of the time I get this error:

> An unhandled exception of type 'System.BadImageFormatException' occurred in Unknown Module.
Duplicate type with name 'Costura.AssemblyLoader' in assembly 'RayCarrot.RCP.Metro, Version=4.0.2.0, Culture=neutral, PublicKeyToken=null'.

At first I thought it was related to Costura, but uninstalling it will give the same error but with "Costura.AssemblyLoader" being replaced by "ProcessedByFody".

For some reason when I build it will sometimes launch once, but then throw this exception whenever I try launching again. Uninstalling the Resource.Embedder fixes this issue completely. It all worked fine yesterday (and earlier today I believe). The only changes I made to my program were adding a few new keys to my resource files.

**Comment by MarcStan** [comment]
`ProcessedByFody` is a class injected by Fody (which itself is used by Costura).

So it sounds to me like this is a problem with Fody/Costura which makes "Uninstalling the Resource.Embedder fixes this issue completely" strange.

From personal experience I would suggest you look into your .csproj file: often times Fody/Costura will leave a Targets directive in there (e.g. after failure during uninstall). The targets directive is then still called even though the nuget package is no longer installed.

They look like this in the csproj:


``` csharp
<Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
  <PropertyGroup>
    <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
  </PropertyGroup>
  <Error Condition="!Exists('..\packages\Fody.4.0.2\build\Fody.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Fody.4.0.2\build\Fody.targets'))" />
  <Error Condition="!Exists('..\packages\Costura.Fody.3.3.3\build\Costura.Fody.props')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Costura.Fody.3.3.3\build\Costura.Fody.props'))" />
</Target>
<Import Project="..\packages\Fody.4.0.2\build\Fody.targets" Condition="Exists('..\packages\Fody.4.0.2\build\Fody.targets')" />
```

To get it cleaned up you can try:

* Remove everything that is Fody/Custora related from csproj and nuget package.config
* clean bin/obj dirs 
* restart Visual Studio as well (or at least the 4+ lingering msbuild.exe processes as they cache the fody tasks in memory)

If you reinstall Costura afterwards it should work correctly again.

My Resource Embedder works similar but it injects a class named "ResourceEmbedderILInjected" as you can see below:

![1](https://user-images.githubusercontent.com/8313404/54772486-59644d00-4bff-11e9-96fd-1462c17b39a7.png)

**Comment by RayCarrot** [comment]
I have already tried removing those parts of the .csproj file, but not for all my projects. Tried that + reinstalling all Fody packages and no change. While they were uninstalled the program worked fine. I then tried uninstalling your package (while keeping Fody) and it works again.
So something is going on between your package and Fody, which is odd since it worked fine a few days ago. I even tried going back to an older version of my solution from GitHub, but same issue. So I'm pretty clueless as to what is actually going on here.

I don't know if this matters, but I have some references which themselves have localized libraries they create (in the region sub-directories in the output). I noticed this when uninstalling Fody.Costura.

The odd thing also is how this doesn't happen every time I launch the program. Usually after I rebuild I can launch the program once first. Then when relaunching it doesn't work, so matter how many times I try. When launching in VS I see the exception, and doing it outside of VS doesn't give my anything. I also tried moving the .exe file to another directory before launching it in case it was loading in some reference from the output directory (which doesn't make any sense since there are only .xml files and the debug file there), but same issue.

**Comment by MarcStan** [comment]
Considering the assembly name `RayCarrot.RCP.Metro` from the first post, I assume [this repository](https://github.com/RayCarrot/Rayman-Control-Panel-Metro) is the right one?

I checked out the `RayCarrot.RCP.Updater.csproj` file and I can see 

``` xml
<!-- top of file -->
<Import Project="..\..\..\packages\Costura.Fody.3.3.3\build\Costura.Fody.props" Condition="Exists('..\..\..\packages\Costura.Fody.3.3.3\build\Costura.Fody.props')" />
<!-- bottom of file -->
<Import Project="..\packages\Costura.Fody.3.1.0\build\Costura.Fody.targets" Condition="Exists('..\packages\Costura.Fody.3.1.0\build\Costura.Fody.targets')" />
  <Import Project="..\packages\Fody.3.2.0\build\Fody.targets" Condition="Exists('..\packages\Fody.3.2.0\build\Fody.targets')" />
<Import Project="..\..\..\packages\Fody.4.0.2\build\Fody.targets" Condition="Exists('..\..\..\packages\Fody.4.0.2\build\Fody.targets')" />
```

Looks to me like you are loading 2 different Fody and 2 different Costura versions at the same time which will be the cause of the problem.

Even if you just want to build the GUI project, internally all MSBuild tasks of a solution are loaded into the same build process and **never unloaded** (unless you kill msbuild.exe/close Visual Studio).

So as soon as the updater is built once it will try to load two seperate Fody/Costura versions and I imagine they create the problems you see as a sideeffect for the GUI project as well.

I would suggest you clean this up & restart Visual Studio and then your metro project should build again.

**Comment by RayCarrot** [comment]
Hm, not sure I follow. Those parts of the file you saw are probably just leftovers from older versions. I deleted all of this since then, just haven't pushed it to GitHub since I've been wanting so solve this issue.
Regarding the updater, that is irrelevant since there is no reference to it from the main program (RayCarrot.RCP.Metro). The updater I just deploy as an executable and manually add to the main program. I tried rebuilding it and adding the one which references the newest versions of Fody, but same issue.

**Comment by MarcStan** [comment]
I see.

When you get an executable that crashes can you use [dnSpy](https://github.com/0xd4d/dnSpy) to look at it (or upload the exe somewhere so I can have a look)? Specifically I would like to known if it contains the "Costura.AssemblyLoader" or other Fody/Costura classes.

The build log from Visual Studio Output could help as well if you can attach that as well.

**Comment by RayCarrot** [comment]
After some more testing it seems like this is what happens:
- I rebuild the project
- If I run the program from outside of VS it works
- If I run it from VS it has a 50% chance of deciding to rebuild two of the four projects before running. This results in the new executable to throw this exception and have an additional 3kb of data (probably the duplicated assemblies/types?)

Since I don't have dnSpy I'm sending the two versions of the executable, one which works and the other one which doesn't:

[Executable files.zip](https://github.com/MarcStan/Resource.Embedder/files/2994067/Executable.files.zip)

Build log (upon manual rebuild):

> 1>------ Rebuild All started: Project: RayCarrot.Windows.Shell, Configuration: Release Any CPU ------
2>------ Rebuild All started: Project: RayCarrot.Rayman, Configuration: Release Any CPU ------
2>C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\Rayman Control Panel\RayCarrot.Rayman\RayCarrot.Rayman\RayCarrot.Rayman.csproj : warning NU1701: Package 'ini-parser 2.5.2' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
2>RayCarrot.Rayman -> C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\Rayman Control Panel\RayCarrot.Rayman\RayCarrot.Rayman\bin\Release\netstandard2.0\RayCarrot.Rayman.dll
2>Done building project "RayCarrot.Rayman.csproj".
1>  RayCarrot.Windows.Shell -> C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\Carrot Framework Extensions\RayCarrot.Windows.Shell\bin\Release\RayCarrot.Windows.Shell.dll
3>------ Rebuild All started: Project: RayCarrot.WPF, Configuration: Release Any CPU ------
3>  RayCarrot.WPF -> C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\Carrot WPF\RayCarrot.WPF\bin\Release\RayCarrot.WPF.dll
4>------ Rebuild All started: Project: RayCarrot.RCP.Metro, Configuration: Release Any CPU ------
4>C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\Rayman Control Panel\RCP Metro\RayCarrot.RCP.Metro\ViewModels\Pages\SettingsPageViewModel.cs(46,27,46,54): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
4>C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\Rayman Control Panel\RCP Metro\RayCarrot.RCP.Metro\ViewModels\Pages\SettingsPageViewModel.cs(46,27,46,54): warning CS1998: This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
4>  Looking for references in: C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\Rayman Control Panel\RCP Metro\RayCarrot.RCP.Metro\bin\Release, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\ByteSize.1.3.0\lib\net45, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\ControlzEx.3.0.2.4\lib\net462, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Costura.Fody.3.3.3\lib\net40, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\Files, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\ini-parser.2.5.2\lib\net20, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\MahApps.Metro.1.6.5\lib\net47, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\MahApps.Metro.IconPacks.Material.2.3.0\lib\net46, C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2, C:\Program Files (x86)\Microsoft SDKs\Expression\Blend\.NETFramework\v4.5\Libraries, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.Configuration.Abstractions.2.2.0\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.Configuration.Binder.2.2.0\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.Configuration.2.2.0\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.DependencyInjection.Abstractions.2.2.0\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.DependencyInjection.2.2.0\lib\net461, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.Logging.Abstractions.2.2.0\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.Logging.Configuration.2.2.0\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.Logging.Console.2.2.0\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.Logging.Debug.2.2.0\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.Logging.2.2.0\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.Logging.EventLog.2.2.0\lib\net461, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.Options.ConfigurationExtensions.2.2.0\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.Options.2.2.0\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.Primitives.2.2.0\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Bcl.Async.1.0.168\lib\net40, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Win32.Registry.4.5.0\lib\net461, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft-WindowsAPICodePack-Core.1.1.3.3\lib\net452, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft-WindowsAPICodePack-Shell.1.1.3.3\lib\net452, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\NAudio.1.8.5\lib\net35, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\NAudio.Vorbis.1.0.0.0\lib\net35, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Newtonsoft.Json.12.0.1\lib\net45, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Nito.AsyncEx.4.0.1\lib\net45, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\NVorbis.0.8.6\lib\net35, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\PropertyChanged.Fody.2.6.0\lib\net452, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\RayCarrot.CarrotFramework.2.1.1\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\Rayman Control Panel\RayCarrot.Rayman\RayCarrot.Rayman\bin\Release\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\RayCarrot.UserData.2.0.3\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\RayCarrot.Windows.Registry.2.0.1\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\Carrot Framework Extensions\RayCarrot.Windows.Shell\bin\Release, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\Carrot WPF\RayCarrot.WPF\bin\Release, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\System.Buffers.4.5.0\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\System.ComponentModel.Annotations.4.5.0\lib\net461, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\System.Diagnostics.EventLog.4.5.0\lib\net461, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\System.Memory.4.5.2\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\System.Numerics.Vectors.4.5.0\lib\net46, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\System.Runtime.CompilerServices.Unsafe.4.5.2\lib\netstandard2.0, C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\Facades, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\Files\WinRT, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\System.Security.AccessControl.4.5.0\lib\net461, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\System.Security.Permissions.4.5.0\lib\net461, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\System.Security.Principal.Windows.4.5.1\lib\net461, C:\Program Files (x86)\Windows Kits\10\UnionMetadata\Facade, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\XamlAnimatedGif.1.2.1\lib\net45
4>  Rewritting pdb
4>  Finished embedding cultures: sv-SE into RayCarrot.RCP.Metro.exe in 508ms
4>  RayCarrot.RCP.Metro -> C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\Rayman Control Panel\RCP Metro\RayCarrot.RCP.Metro\bin\Release\RayCarrot.RCP.Metro.exe
4>  CleanupAfterCoreBuild
4>  Deleted resource file 'sv-SE' as it was embedded into the target.
4>  Deleted resource directory 'sv-SE' as it is empty.
========== Rebuild All: 4 succeeded, 0 failed, 0 skipped ==========

Build log (upon attempting to run):

> 1>------ Build started: Project: RayCarrot.WPF, Configuration: Release Any CPU ------
1>  RayCarrot.WPF -> C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\Carrot WPF\RayCarrot.WPF\bin\Release\RayCarrot.WPF.dll
2>------ Build started: Project: RayCarrot.RCP.Metro, Configuration: Release Any CPU ------
2>  Looking for references in: C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\Rayman Control Panel\RCP Metro\RayCarrot.RCP.Metro\bin\Release, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\ByteSize.1.3.0\lib\net45, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\ControlzEx.3.0.2.4\lib\net462, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Costura.Fody.3.3.3\lib\net40, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\Files, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\ini-parser.2.5.2\lib\net20, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\MahApps.Metro.1.6.5\lib\net47, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\MahApps.Metro.IconPacks.Material.2.3.0\lib\net46, C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2, C:\Program Files (x86)\Microsoft SDKs\Expression\Blend\.NETFramework\v4.5\Libraries, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.Configuration.Abstractions.2.2.0\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.Configuration.Binder.2.2.0\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.Configuration.2.2.0\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.DependencyInjection.Abstractions.2.2.0\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.DependencyInjection.2.2.0\lib\net461, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.Logging.Abstractions.2.2.0\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.Logging.Configuration.2.2.0\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.Logging.Console.2.2.0\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.Logging.Debug.2.2.0\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.Logging.2.2.0\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.Logging.EventLog.2.2.0\lib\net461, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.Options.ConfigurationExtensions.2.2.0\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.Options.2.2.0\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Extensions.Primitives.2.2.0\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Bcl.Async.1.0.168\lib\net40, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft.Win32.Registry.4.5.0\lib\net461, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft-WindowsAPICodePack-Core.1.1.3.3\lib\net452, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Microsoft-WindowsAPICodePack-Shell.1.1.3.3\lib\net452, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\NAudio.1.8.5\lib\net35, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\NAudio.Vorbis.1.0.0.0\lib\net35, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Newtonsoft.Json.12.0.1\lib\net45, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\Nito.AsyncEx.4.0.1\lib\net45, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\NVorbis.0.8.6\lib\net35, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\PropertyChanged.Fody.2.6.0\lib\net452, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\RayCarrot.CarrotFramework.2.1.1\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\Rayman Control Panel\RayCarrot.Rayman\RayCarrot.Rayman\bin\Release\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\RayCarrot.UserData.2.0.3\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\RayCarrot.Windows.Registry.2.0.1\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\Carrot Framework Extensions\RayCarrot.Windows.Shell\bin\Release, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\Carrot WPF\RayCarrot.WPF\bin\Release, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\System.Buffers.4.5.0\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\System.ComponentModel.Annotations.4.5.0\lib\net461, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\System.Diagnostics.EventLog.4.5.0\lib\net461, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\System.Memory.4.5.2\lib\netstandard2.0, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\System.Numerics.Vectors.4.5.0\lib\net46, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\System.Runtime.CompilerServices.Unsafe.4.5.2\lib\netstandard2.0, C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\Facades, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\Files\WinRT, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\System.Security.AccessControl.4.5.0\lib\net461, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\System.Security.Permissions.4.5.0\lib\net461, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\System.Security.Principal.Windows.4.5.1\lib\net461, C:\Program Files (x86)\Windows Kits\10\UnionMetadata\Facade, C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\packages\XamlAnimatedGif.1.2.1\lib\net45
2>  Rewritting pdb
2>  Finished embedding cultures: sv-SE into RayCarrot.RCP.Metro.exe in 495ms
2>  RayCarrot.RCP.Metro -> C:\Users\RayCarrot\Desktop\Allt som jag bryr mig om\Visual Studio\Rayman Control Panel\RCP Metro\RayCarrot.RCP.Metro\bin\Release\RayCarrot.RCP.Metro.exe
2>  CleanupAfterCoreBuild
2>  Deleted resource file 'sv-SE' as it was embedded into the target.
2>  Deleted resource directory 'sv-SE' as it is empty.
========== Build: 2 succeeded, 0 failed, 2 up-to-date, 0 skipped ==========

**Comment by MarcStan** [comment]
As suspected: The Costura code is indeed embedded twice in the exe (top is the broken one, bottom is the working exe):

![1](https://user-images.githubusercontent.com/8313404/54788099-d3a7c800-4c25-11e9-88d1-a0040867902f.png)

I managed to reproduce with a WPF project as well: Anytime the project is built (using **build** and not rebuild!) the exe grows by ~1kb and another Costura AssemblyLoader is added.

Costura doesn't check if it has already embedded its code and just blindly adds it again on every build.

Normally this isn't a problem because Visual Studio will either recognize that the code wasn't modified and skip building, or do a clean & rebuild.

Unfortunately the way my Resource Embedder works, it needs to modify the exe **after** the Visual Studio build is finished (and has noted the exe state) thus for Visual Studio the exe is always out of sync and Visual Studio wants to build it again (e.g. anytime you want to run it).

These factors in combination lead to the broken behaviour.

I managed to track down the change to Fody >= 4.X.

If you downgrade Fody to 3.3.5 (which requires at most Costura 3.3.2) then this issue should no longer happen (in my WPF project everything worked again).

I will probably have to do a PR with Fody to fix this. But for now the Fody downgrade should suffice as a workaround.

Let me know if it doesn't.

**Comment by RayCarrot** [comment]
Ah, that makes sense. Thanks for getting to the bottom of the issue! I downgraded as you suggested and it all works fine now.

**Comment by Otiel** [comment]
>I will probably have to do a PR with Fody to fix this. But for now the Fody downgrade should suffice as a workaround.

Is there an issue or PR already opened in the Fody repository? I couldn't find any reference to this problem.

**Comment by MarcStan** [comment]
Sorry, I haven't created a PR or issue with Fody as the issue dropped of my radar and Fody requires [payment](https://github.com/Fody/Home/blob/master/pages/licensing-patron-faq.md) as of version 3.3.3 (for issues, contributions and usage).

I think the fix would resolve around a safeguard against [adding the type](https://github.com/Fody/Costura/blob/1b25844f04d674ca8070c3578a58456d180b4200/Costura.Fody/AssemblyLoaderImporter.cs#L59) when it already exists but I haven't tested that to confirm.

Personally I am not doing a lot of desktop development anymore (main reason why I created this project) and I don't actively use any embedding for xamarin/web applications (as the dll's aren't user facing) so my usecase for resource embedding has essentially disappeared.

For the future I'm hoping [single-file distribution](https://github.com/dotnet/coreclr/issues/20287) will be natively supported in .Net Core - making my project obsolete.

**Comment by RayCarrot** [comment]
They do however state the following:

> Issues from non-Patrons, that are bugs and are highly likely to effect the larger Fody user base, may justify the effort and be handled.

The .Net Core feature sounds promising, but that might take a while to happen (if ever).

**Comment by RayCarrot** [comment]
Hey again!
Just wanted to say that it seems recent versions of Fody have solved the issue. Instead of duplicating the types it now just gives me this warning:

> Fody: The assembly has already been processed by Fody. Weaving aborted.

Then it compiles just fine. For reference I'm using 5.0.6.

**Comment by AndnixSH** [comment]
I had the same problem

I followed the steps by MarcStan and it worked again

https://github.com/MarcStan/resource-embedder/issues/13#issuecomment-475330381

**Comment by AndnixSH** [comment]
I had the same problem
I followed the steps by MarcStan but didn't work. Don't wanna downgrade cuz it might make another unexpected behavoiur
I'm using Fody 6.1.2 and Costura 4.1.0
