### ISSUE TITLE
Suppress "Could not determine version of assembly" warning

### ISSUE THREAD

**Issue by Otiel** [MarcStan/Resource.Embedder#17]
**Issue**

I'm getting the following warning on my solution since a couple days:
>Could not determine version of assembly. If you are compiling an assembly targeting an older version than .Net 4 then resources will not work (consider removing Resource.Embedder from that project). If you are targeting .Net 4 or above, everything should be fine. See `https://github.com/MarcStan/Resource.Embedder/issues/3` for details.

Looking at my git log, nothing that looks of importance changed regarding this, thus I'm not sure why I'm getting this warning now and not before.

Is there any configuration to add in order to inform Resource.Embedder of the targeted .NET version?

**Details:**

  - .Net Version: .NET Framework 4.7.2
  - Platform/OS Version: Windows 10 1809 (build 17763.503) / Visual Studio 2019 v16.1.1

**Comment by MarcStan** [comment]
This is a bug on my end. I was looking for corflags.exe using a pathlist and didn't update to [include .Net 4.7.2](https://github.com/MarcStan/Resource.Embedder/blob/master/src/ResourceEmbedder.MsBuild/WindowsSdkHelper.cs#L19).

I assume you only had .Net 4.7.2 installed on your system.

I fixed it by using a simpler check that no longer depends on corflags.exe. If you update to 2.0.1 it should work again.

**Comment by Otiel** [comment]
Thanks for the fix, I confirm it's all good now in 2.0.1.

>I assume you only had .Net 4.7.2 installed on your system.

Yes exactly. Uninstalling VS 2017 probably removed a previous version of the .NET Framework I had installed before.
