### ISSUE TITLE
F# support

### ISSUE THREAD

**Issue by yuyoyuppe** [MarcStan/Resource.Embedder#4]
> Nothing to embed! Skipping N:\test\obj\Release\test.exe

However, _there is_ something to embed :)

**Comment by MarcStan** [comment]
Can you provide more details? I'm not really familar with the whole F# toolchain.
How are you adding the localization files? What type of project are you using?

I just created a new F# library & console application.
After adding 2 .resx files to each (english & german) and adding the Resource.Embedder nuget package I end up with an exe and a dll that both have their resources embedded:

```
1>	Rewritting pdb
1>	Finished embedding cultures: de into FSharpLibrary.dll in 89ms
1>	FSharpLibrary -> C:\Projects\FSharpConsole\FSharpLibrary\bin\Debug\FSharpLibrary.dll
1>	Deleted resource file 'de' as it was embedded into the target.
1>	Deleted resource directory 'de' as it is empty.
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```
